/**
 * documentStore.js
 *
 * In-memory store for assembled documents with 30-minute TTL.
 * Used by the multi-node path to offer file downloads via
 * `document_ready` SSE events instead of streaming raw text.
 *
 * Tokens are UUID v4 generated by crypto.randomUUID() (Node 20+).
 */

import crypto from 'node:crypto';

const store = new Map(); // token → { content, filename, contentType, expiresAt }

const TTL_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Stores a document and returns a download token.
 * Schedules automatic cleanup after 30 minutes.
 *
 * @param {{ content: string, filename: string }} doc
 * @returns {string} UUID download token
 */
export function storeDocument({ content, filename }) {
  const token = crypto.randomUUID();
  const contentType = filename.endsWith('.json') ? 'application/json' : 'text/markdown';
  store.set(token, {
    content,
    filename,
    contentType,
    expiresAt: Date.now() + TTL_MS,
  });
  // Schedule cleanup
  setTimeout(() => store.delete(token), TTL_MS);
  return token;
}

/**
 * Retrieves a stored document by token.
 * Returns null if the token is unknown or expired.
 *
 * @param {string} token - UUID download token
 * @returns {{ content: string, filename: string, contentType: string } | null}
 */
export function getDocument(token, _now = Date.now()) {
  const doc = store.get(token);
  if (!doc) return null;
  if (_now > doc.expiresAt) {
    store.delete(token);
    return null;
  }
  return { content: doc.content, filename: doc.filename, contentType: doc.contentType };
}

/**
 * Clears all stored documents. Used for test cleanup.
 */
export function clearStore() {
  store.clear();
}
